#Defining Sample Dataset
DNA_original = "TTTGAACCGTCAGCGGTGCGCTGTGTGGTACCGGCGTTGAAAGTTGGGTACATTTGAGTACGTCTGCGCGAGGCATACTCAGTCTAGTGTGACTGAATACAGCGTGGCAGTTAATGCAGTTCGGGTCTACGGTTGTCCCACTCTTCGTCATTCATTGGTAGCCAGATACACATGCGCAGCTAAATGACCAAGGCTAATCCGGGTGTAGCCCTTCTTCGTTACGTGCAACTGAGCCGGAAGATGGTGATACTTGCGGACCCCCCGTGCACCGGTTCCACTGTAGCATGTACCCCACTACCTTGGCCGCAAGCGCCTGAGTCCGCATGGCTTTCCAGAAAACGTGCAACAGTGGGGAGAAGCCACAACCAAGCGAGTAGAGGCGAGGGATAGTCAAGACAAGGCAAACACAAATTGGCCCTTGCTACTTGTCCCTACCTACCTGATGCCACTGTTAGTTCCGATGTAATCATATTCACCGTGTGGATACAAGGGGGCGCGATTCCGACCATCTTACGGGGGGTTTCGCTTCCTTGGCAGTGAGAGCTCCATCCATGACGACTGTGCAGAGCATTATCGTAGAGTTTACAAGCTTATGAGGCCTACAGCGCGAGCCCGCTGGATCAGCACGATTCGTCGTCGTTCTTGCTGTGAAACGTATTTATCGTAAGGTTGGGTCCGACATCAGGCCTGGGAGGGTGAGCACAAGCCTTTCCTACGCTGCTGAGCTACCCCCACATGATTGGCCGCAATCTCCTATGCCGACGCTTGAGTCATAATTTCAAGCGAACGGACGGTTTCAACTGTCTTAGCTTGT"
#Printing original Dataset
print ("The original DNA string is : " + str(DNA_original))
#Replacing nt for creating reverse complementay strand
replace = DNA_original.replace("A", "%temp%").replace("T", "A").replace("%temp%", "T").replace("C", "%temp2%").replace("G", "C").replace("%temp2%", "G")
#Printing complementary strand
Sample_output = replace
stringlenght=len(Sample_output)
slicedString=Sample_output[stringlenght::-1]
print ("The Sample Output is: " + slicedString)