import collections

Nucleotides = ["A", "C", "T", "G"]

def validateSeq2(DNA_sequence):
        tmpseq = DNA_sequence.upper()
        for nt in tmpseq:
            if nt not in Nucleotides:
                return False
        return tmpseq

def CountNt(seq):
    return dict(collections.Counter(seq))


def CountNt2(seq):
    


DNAseq = "GGGCGCCATGGCTCGGACCCCTGAGAGTTGACAATCCATTGCGAGCTATAGTGACTCGATTGTTAGAATTGCCTGCAATGATAATGACTCCCCCTGCAGAGGCAGAGGGACTTTTCCCCACCACTCGCCCGCACGCGTAACGTATAAACACTAGGCGTCTGCTCTTATGACAGCGAAGAACCAATGGCGCGGCCTCGTCAGCTGAGGGGATCTGTACCCCTATACGAACCGGAAGGTGAGAGTTCCCGATCAAGGGCGAACAGGGCGCAACGTAGACTAGCTCTCGTGGGTGAGAAGTTACGATGATGCCGGTAACGAAGGCAAGGGACGACAACAGATTCCTAGATAAACTCGGAAAGGGGTACAAAGCATGTACTAGCCCTCGCAGAACATGTCAAACACCCAGATTTTAACCTGCGGTCAACTGTCTCTTTGCTGCACTAAATTGTACATCTGGATGGCGGATGCAATCATGCGATCCATAAATGCGCCCGTACCACCATCGACTGACACTTAGGTAAGAAACCTCGTTCGGCCAACCAGGAAAAATTCCTTGTAAGTTGATCCCTTTGGTCACCGGGGTTAAGCTGGTAATAACGAATCCCTGCTGCGCACCGAGTCCGCAATATTATCCGCATAGATCGCTTTGCAGTGCACAAGTACAGAGGCTCTTGCTCATTAAGGGCCGATGTGTTGCGTCATCCTCAGCAACTGAATGTCAAACCGAGCGAGCGCCTTTTCAACAGCAGCTAGACTAAAGGTATTGGCCCAGTTTACTCCACCGGCCACAAACAAATTATCCTACAATGTGAACGCGACTCGTTCGAGA"


print (CountNt(DNAseq))